# Generated by Django 2.1.5 on 2021-02-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210220_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='author',
        ),
    ]
