# Generated by Django 2.1.5 on 2021-02-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
