# Generated by Django 2.1.5 on 2021-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='img/icon/default.png', upload_to='img/'),
        ),
    ]
