# Generated by Django 2.1.5 on 2021-02-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210214_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
